Fix installation of pufferd to not include deleted column

diff --git a/pufferpanel b/pufferpanel
--- a/pufferpanel
+++ b/pufferpanel
@@ -388,10 +388,15 @@ case $1 in
             sed -e "s/{{ settings.master_url }}/http:\/\/${siteUrl}/g" app/views/templates/auto-deploy.tpl | sed -e "s/{{ node.daemon_secret }}/${nodeSecret}/g" > /tmp/pufferd.sh
             chmod +x /tmp/pufferd.sh
             /tmp/pufferd.sh
+            installWorked=$?
             rm /tmp/pufferd.sh
-            mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
-                INSERT INTO nodes (name, location, fqdn, ip, daemon_secret,daemon_listen,daemon_sftp, daemon_base_dir, allocate_memory, allocate_disk, ips, ports, public, docker)
-                VALUES('LocalNode', (SELECT id FROM locations WHERE short = 'Localhost'), '${siteUrl}', '127.0.0.1', '${nodeSecret}', 5656, 5657, '/srv/pufferd', 0, 0, '{}', '{}', 1, 0)"
+            if [ $installWorked -eq 0 ]; then
+                mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
+                    INSERT INTO nodes (name, location, fqdn, ip, daemon_secret,daemon_listen,daemon_sftp, allocate_memory, allocate_disk, ips, ports, public, docker)
+                    VALUES('LocalNode', (SELECT id FROM locations WHERE short = 'Localhost'), '${siteUrl}', '127.0.0.1', '${nodeSecret}', 5656, 5657, 0, 0, '{}', '{}', 1, 0)"
+            else
+                echo "${red}Installation of pufferd failed locally, you will have to create a node manually on this machine if needed"
+            fi
         fi
 
         printSeparator
